/* js/menu.js - Auto-generated by Python */

const subjectSettings = {
    english: { name: "English", icon: "A", colorClass: "subject-english", description: "単語・長文" },
    math:    { name: "Math",     icon: "∑", colorClass: "subject-math",    description: "数学" },
    japanese:{ name: "Japanese", icon: "文", colorClass: "subject-kokugo",  description: "現代文・古文・漢文" },
    science: { name: "Science",  icon: "🧪", colorClass: "subject-science", description: "物理・化学・地学・生物" },
    social:  { name: "Social",   icon: "🏛️", colorClass: "subject-social",  description: "歴史・地理" },
    info:    { name: "Info",     icon: "💻", colorClass: "subject-info",    description: "情報" }
};

const menuData = [{"id": "english", "title": "Unit7 英単語テスト", "file": "english/unit7-word/index.html", "category": "Vocabulary", "icon": "単"}, {"id": "math", "title": "2025年6月数学: ベクトル", "file": "math/202506-vector/index.html", "category": "Vector", "icon": "↗️"}, {"id": "japanese", "title": "2025年12月 文学基礎統一テスト", "file": "japanese/202512-kanbun/index.html", "category": "漢文", "icon": "漢"}, {"id": "japanese", "title": "2025年9月 文学基礎統一テスト", "file": "japanese/202509-kobun/index.html", "category": "古文", "icon": "古"}, {"id": "japanese", "title": "2025年6月 古文統一テスト", "file": "japanese/202506-kobun/index.html", "category": "古文", "icon": "古"}, {"id": "science", "title": "2025年12月 地学統一テスト", "file": "science/202512-earth_science/index.html", "category": "Earth Science", "icon": "🌏"}, {"id": "science", "title": "2025年9月 地学統一テスト", "file": "science/202509-earth_science/index.html", "category": "Earth Science", "icon": "🌏"}, {"id": "science", "title": "2025年9月 生物統一テスト", "file": "science/202509-biology/index.html", "category": "Biology", "icon": "🧬"}, {"id": "science", "title": "2025年6月 地学統一テスト", "file": "science/202506-earth_science/index.html", "category": "Earth Science", "icon": "🌏"}, {"id": "science", "title": "2025年6月 化学統一テスト", "file": "science/202506-chemistry/index.html", "category": "Chemistry", "icon": "🧪"}];
