/* js/menu.js - Auto-generated by Python */

// 教科ごとの設定
const subjectSettings = {
    english: { name: "English", icon: "A", colorClass: "subject-english", description: "単語・長文" },
    math:    { name: "Math",     icon: "∑", colorClass: "subject-math",    description: "数学I・A・II・B" },
    kokugo:  { name: "国語",      icon: "文", colorClass: "subject-kokugo",  description: "現代文・古文・漢文" },
    science: { name: "Science",  icon: "🧪", colorClass: "subject-science", description: "物理・化学・地学" },
    social:  { name: "Social",   icon: "🏛️", colorClass: "subject-social",  description: "歴史・地理" },
    info:    { name: "Info",     icon: "💻", colorClass: "subject-info",    description: "情報・プログラミング" }
};

// 自動生成されたページリスト
const menuData = [{"id": "english", "title": "Unit7 英単語テスト", "file": "english/unit7-word/index.html"}, {"id": "science", "title": "2025年12月 地学統一テスト", "file": "science/202512-earth_science/index.html"}];
