import os
import re

# ==========================================
# 設定エリア
# ==========================================
OUTPUT_FILE = "js/menu.js"

TARGET_DIRS = {
    "english": "english",
    "math": "math",
    "japanese": "japanese",
    "science": "science",
    "social": "social",
    "info": "info"
}

# ★修正箇所: キーワードに対応する「表示名」と「アイコン」を設定
SUB_CATEGORY_RULES = {
    # 理科
    "chemistry":     {"label": "Chemistry",     "icon": "🧪"}, # 試験管
    "earth_science": {"label": "Earth Science", "icon": "🌏"}, # 地球
    "biology":       {"label": "Biology",       "icon": "🧬"}, # DNA
    "physics":       {"label": "Physics",       "icon": "⚡"}, # 雷
    
    # 国語
    "kanbun":        {"label": "漢文",          "icon": "漢"}, # 漢字の「漢」
    "kobun":         {"label": "古文",          "icon": "古"}, # 漢字の「古」
    "gendai":        {"label": "現代文",        "icon": "現"}, 
    
    # 数学
    "vector":        {"label": "Vector",        "icon": "↗️"}, 
    "calulus":       {"label": "Calculus",      "icon": "∫"},  
    
    # 英語
    "word":          {"label": "Vocabulary",    "icon": "単"},
    "reading":       {"label": "Reading",       "icon": "読"},
}

# ==========================================
# 処理ロジック
# ==========================================

def get_html_title(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            match = re.search(r'<title>(.*?)</title>', content, re.IGNORECASE | re.DOTALL)
            if match:
                return match.group(1).strip()
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
    return "No Title"

def get_category_info(file_path):
    """パスから詳細なカテゴリ名とアイコンを取得する"""
    lower_path = file_path.lower()
    
    for key, info in SUB_CATEGORY_RULES.items():
        if key in lower_path:
            return info # {"label": "...", "icon": "..."} を返す
    
    return None

def generate_menu_js():
    menu_data = []
    print("--- Scanning directories ---")

    for folder, subject_id in TARGET_DIRS.items():
        if not os.path.exists(folder):
            continue

        # 日付順（新しい順）にソート
        for item in sorted(os.listdir(folder), reverse=True):
            item_path = os.path.join(folder, item)

            if os.path.isdir(item_path):
                html_path = os.path.join(item_path, "index.html")
                
                if os.path.exists(html_path):
                    title = get_html_title(html_path)
                    web_path = html_path.replace(os.sep, '/')
                    
                    # ★カテゴリ情報（名前とアイコン）を取得
                    cat_info = get_category_info(web_path)

                    print(f"Found: [{subject_id}] {title}")
                    
                    data = {
                        "id": subject_id,
                        "title": title,
                        "file": web_path
                    }
                    
                    # 詳細情報があればデータに追加
                    if cat_info:
                        data["category"] = cat_info["label"]
                        data["icon"] = cat_info["icon"]  # ★アイコンも追加

                    menu_data.append(data)

    js_content = f"""/* js/menu.js - Auto-generated by Python */

const subjectSettings = {{
    english: {{ name: "English", icon: "A", colorClass: "subject-english", description: "単語・長文" }},
    math:    {{ name: "Math",     icon: "∑", colorClass: "subject-math",    description: "数学" }},
    japanese:{{ name: "Japanese", icon: "文", colorClass: "subject-kokugo",  description: "現代文・古文・漢文" }},
    science: {{ name: "Science",  icon: "🧪", colorClass: "subject-science", description: "物理・化学・地学・生物" }},
    social:  {{ name: "Social",   icon: "🏛️", colorClass: "subject-social",  description: "歴史・地理" }},
    info:    {{ name: "Info",     icon: "💻", colorClass: "subject-info",    description: "情報" }}
}};

const menuData = {str(menu_data).replace("'", '"').replace("None", "null")};
"""

    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(js_content)
        print(f"\nSuccessfully updated {OUTPUT_FILE}!")
    except Exception as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    generate_menu_js()