import os
import re

# ==========================================
# 設定エリア
# ==========================================
OUTPUT_FILE = "js/menu.js"

# フォルダとIDの対応
TARGET_DIRS = {
    "english": "english",
    "math": "math",
    "japanese": "japanese",
    "science": "science",
    "social": "social",
    "info": "info"
}

# ==========================================
# 処理ロジック
# ==========================================

def get_html_title(file_path):
    """HTMLファイルから<title>タグの中身を抽出する"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
            match = re.search(r'<title>(.*?)</title>', content, re.IGNORECASE | re.DOTALL)
            if match:
                return match.group(1).strip()
    except Exception as e:
        print(f"Error reading {file_path}: {e}")
    return "No Title"

def generate_menu_js():
    menu_data = []
    print("--- Scanning directories (Nested Structure) ---")

    for folder, subject_id in TARGET_DIRS.items():
        if not os.path.exists(folder):
            continue

        # 1. 教科フォルダの中身を走査
        for item in os.listdir(folder):
            item_path = os.path.join(folder, item)

            # 2. それが「ディレクトリ（単元フォルダ）」であるか確認
            if os.path.isdir(item_path):
                # 3. その中に 'index.html' があるか確認
                html_path = os.path.join(item_path, "index.html")
                
                if os.path.exists(html_path):
                    # タイトル取得
                    title = get_html_title(html_path)
                    
                    # Web用パスに変換 (Windowsのバックスラッシュ対策)
                    web_path = html_path.replace(os.sep, '/')
                    
                    print(f"Found: [{subject_id}] {title} -> {web_path}")
                    
                    menu_data.append({
                        "id": subject_id,
                        "title": title,
                        "file": web_path
                    })

    # JSファイル書き出し
    js_content = f"""/* js/menu.js - Auto-generated by Python */

// 教科ごとの設定
const subjectSettings = {{
    english: {{ name: "English", icon: "A", colorClass: "subject-english", description: "単語・長文" }},
    math:    {{ name: "Math",     icon: "∑", colorClass: "subject-math",    description: "数学I・A・II・B" }},
    kokugo:  {{ name: "国語",      icon: "文", colorClass: "subject-kokugo",  description: "現代文・古文・漢文" }},
    science: {{ name: "Science",  icon: "🧪", colorClass: "subject-science", description: "物理・化学・地学" }},
    social:  {{ name: "Social",   icon: "🏛️", colorClass: "subject-social",  description: "歴史・地理" }},
    info:    {{ name: "Info",     icon: "💻", colorClass: "subject-info",    description: "情報・プログラミング" }}
}};

// 自動生成されたページリスト
const menuData = {str(menu_data).replace("'", '"')};
"""

    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(js_content)
        print(f"\nSuccessfully updated {OUTPUT_FILE}!")
    except Exception as e:
        print(f"Error writing file: {e}")

if __name__ == "__main__":
    generate_menu_js()